apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sharkeysocial
  namespace: sharkeysocial
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharkeysocial
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sharkeysocial-federation
  namespace: sharkeysocial
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sharkeysocial-federation
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100

